### ISSUE TITLE
node-redis support

### ISSUE THREAD

**Issue by bard** [microlinkhq/async-ratelimiter#22]
Following up from https://github.com/microlinkhq/async-ratelimiter/issues/19#issuecomment-484870327, async-ratelimiter does not work with `node-redis`, only `ioredis`. Probable culprit: https://github.com/microlinkhq/async-ratelimiter/blob/master/src/index.js#L42

**Comment by Kikobeats** [comment]
I'm not interested into support `node-redis` since `ioredis` have all the features necessaries and the project is well maintained 🙂

**Comment by bard** [comment]
That's fair enough.

This module is mentioned as a "Promise version" of `node-ratelimiter` on `node-ratelimiter` page, so people moving from there will come here expecting the same features minus callbacks plus promises, like I did. It might make sense to be explicit about redis client support.
