### ISSUE TITLE
feat: please use `np` for version releases

### ISSUE THREAD

**Issue by titanism** [microlinkhq/async-ratelimiter#40]
The reason being is because the Changelog and Releases are both pretty much empty and contain no information about each release.

See <https://github.com/sindresorhus/np> (use this when you are going to version bump, it'll do it for you).  This is what we use for Tangerine, see <https://github.com/forwardemail/tangerine/releases>.

e.g. both are empty right now: <https://github.com/microlinkhq/async-ratelimiter/blob/master/CHANGELOG.md> and <https://github.com/microlinkhq/async-ratelimiter/releases> and contain no commit information.

**Comment by Kikobeats** [comment]
Yeah, I need to rework the release process. We're delegating into `standard-version` and it's now a deprecated project, so definitively is not reflecting the activity properly.

On the other hand, this project is easy to validate checking commits on GitHub. Most of them are just maintenance, no big rewrites are planned.

Eventually a new tool will be used, and generate a new changelog is very straightforward. It isn't a priority right now, thanks for the suggestion 🙂

**Comment by Kikobeats** [comment]
Probably I'm going to delete all the `CHANGELOG.md` files on my project and just use GitHub Releases.

Plus, GitHub allows to auto-generate the changelog so that will drop `devDependencies` used for parsing, etc.

Less code, less files, happy maintainer 😆
